"""training

Revision ID: 2865a6fe343c
Revises: b618d4b062f2
Create Date: 2024-11-09 20:11:48.276909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2865a6fe343c'
down_revision: Union[str, None] = 'b618d4b062f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('video', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXTREME', name='traininglevels'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uix_name_type'),
    sa.UniqueConstraint('video')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    # ### end Alembic commands ###
