"""fixing

Revision ID: 436a98f6976d
Revises: 682c71c16452
Create Date: 2024-11-09 17:36:00.802194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436a98f6976d'
down_revision: Union[str, None] = '682c71c16452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'phone',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    # ### end Alembic commands ###
