"""training

Revision ID: 5de99afa7c58
Revises: 16443ff8483e
Create Date: 2024-11-09 21:53:48.487646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5de99afa7c58'
down_revision: Union[str, None] = '16443ff8483e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('level', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EXTREME', name='traininglevels'), nullable=False))
    op.drop_constraint('uix_name_type', 'trainings', type_='unique')
    op.create_unique_constraint('uix_name_level', 'trainings', ['name', 'level'])
    op.drop_column('trainings', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('type', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', 'EXTREME', name='traininglevels'), autoincrement=False, nullable=False))
    op.drop_constraint('uix_name_level', 'trainings', type_='unique')
    op.create_unique_constraint('uix_name_type', 'trainings', ['name', 'type'])
    op.drop_column('trainings', 'level')
    # ### end Alembic commands ###
